// Emit the same model as Mermaid, for GitHub.
//
// The SVG is for the site, where we control the page. This is for the repository, where we
// do not: GitHub renders ```mermaid fences natively, so a colleague browsing the code sees
// the diagram without a build step, a plugin, or a trip to the website.
//
// Two renderers, one model. Neither is hand-maintained, and the drift check covers both.

const SHAPE = {
  // Mermaid's node syntax is its own vocabulary of shapes. Map each kind to a distinct one
  // so the GitHub rendering keeps the property that matters most in the SVG: you can tell
  // what something is without reading the legend.
  skill: (id, t) => `${id}["${t}"]`,
  subagent: (id, t) => `${id}(["${t}"])`,
  workflow: (id, t) => `${id}[["${t}"]]`,
  environment: (id, t) => `${id}{{"${t}"}}`,
  service: (id, t) => `${id}>"${t}"]`,
  hook: (id, t) => `${id}[/"${t}"/]`,
};

const STAGE_LABEL = {
  1: 'Plan',
  2: 'Design',
  3: 'Build',
  4: 'Test',
  5: 'Deploy',
  6: 'Maintain',
};

const safeId = (id) => id.replace(/[^A-Za-z0-9]/g, '_');
const clean = (s) =>
  String(s ?? '')
    .replace(/"/g, "'")
    .replace(/\n/g, ' ');

export function renderMermaid({ nodes, annotations }) {
  const ann = annotations;
  const lines = ['flowchart LR'];

  const byStage = new Map();
  const hooks = [];
  for (const n of nodes) {
    const a = ann[n.id];
    if (!a) continue;
    if (n.kind === 'hook') {
      hooks.push(n);
      continue;
    }
    if (a.stage == null) continue;
    if (!byStage.has(a.stage)) byStage.set(a.stage, []);
    byStage.get(a.stage).push({ n, a });
  }

  for (const stage of [1, 2, 3, 4, 5, 6]) {
    const items = byStage.get(stage) ?? [];
    const decisions = (ann._decisions ?? []).filter((d) => d.stage === stage);
    if (!items.length && !decisions.length) continue;

    lines.push(`  subgraph S${stage}["${stage} · ${STAGE_LABEL[stage]}"]`);
    lines.push(`    direction TB`);

    for (const d of decisions) {
      lines.push(`    ${safeId(d.id)}{"${clean(d.label)}"}`);
    }
    for (const { n, a } of items) {
      const trigger = n.triggerText ?? a.trigger;
      const label = trigger
        ? `${clean(n.label)}<br/><small>▸ ${clean(trigger)}</small>`
        : clean(n.label);
      const shape = SHAPE[n.kind] ?? ((id, t) => `${id}["${t}"]`);
      lines.push(`    ${shape(safeId(n.id), label)}`);
    }
    lines.push(`  end`);
  }

  // Hooks are not a stage; they sit under every session.
  lines.push(`  subgraph HOOKS["Hooks · deterministic, not negotiable"]`);
  lines.push(`    direction TB`);
  for (const h of hooks) {
    lines.push(
      `    ${SHAPE.hook(safeId(h.id), `${clean(h.label)}<br/><small>▸ ${clean(h.triggerText)}</small>`)}`,
    );
  }
  lines.push(`  end`);

  // The stage sequence, then the edge that makes it a loop.
  const present = [1, 2, 3, 4, 5, 6].filter(
    (s) => byStage.has(s) || (ann._decisions ?? []).some((d) => d.stage === s),
  );
  for (let i = 0; i < present.length - 1; i++) {
    lines.push(`  S${present[i]} --> S${present[i + 1]}`);
  }
  lines.push(`  S6 -. "a breach becomes the next intent<br/>no tokens, no model" .-> S1`);

  // Styling. Pink is a human decision or the production gate, and nothing else.
  lines.push(`  classDef human fill:none,stroke:#e20074,stroke-width:2px,color:#e20074;`);
  lines.push(`  classDef gate fill:none,stroke:#e20074,stroke-width:2px;`);
  lines.push(`  classDef agent stroke:#315aa1,stroke-width:1.5px;`);
  const humanIds = (ann._decisions ?? []).map((d) => safeId(d.id));
  if (humanIds.length) lines.push(`  class ${humanIds.join(',')} human;`);
  const gateIds = nodes.filter((n) => ann[n.id]?.gate).map((n) => safeId(n.id));
  if (gateIds.length) lines.push(`  class ${gateIds.join(',')} gate;`);
  const agentIds = nodes.filter((n) => ann[n.id]?.cost === 'agent').map((n) => safeId(n.id));
  if (agentIds.length) lines.push(`  class ${agentIds.join(',')} agent;`);

  return lines.join('\n');
}

export function renderMarkdown({ nodes, annotations, mermaid }) {
  const counts = nodes.reduce((acc, n) => ((acc[n.kind] = (acc[n.kind] ?? 0) + 1), acc), {});
  const costed = nodes.filter((n) => annotations[n.id]?.cost === 'agent');

  return `# The pipeline

<!-- GENERATED by \`npm run diagram\` — do not edit by hand. CI fails if this file is stale. -->

Every node below is derived from a file that has to exist for the pipeline to work:
workflows and their triggers, hooks from \`.claude/settings.json\`, skills, subagents, and
\`bands.yaml\`. Nothing here is a hand-kept list, so this diagram cannot describe a pipeline
that is not there.

What the repository cannot state about itself — which stage a thing belongs to, whether it
costs quota, which node is a gate — lives in \`scripts/diagram/annotations.json\`, and
\`npm run diagram\` refuses to run if any derived node lacks an entry.

\`\`\`mermaid
${mermaid}
\`\`\`

## Reading it

- **Pink** marks a human decision or the production gate. Nothing else is pink.
- **▸** is what triggers a thing, not what it does.
- ${Object.entries(counts)
    .map(([k, v]) => `${v} ${k}${v === 1 ? '' : 's'}`)
    .join(', ')}.
- ${costed.length} of them spend Claude quota: ${costed.map((n) => `\`${n.label}\``).join(', ')}. Everything else is free.

A rendered SVG of the same model, themed for light and dark, is on
[the site](https://rashid.fr/sdlc/#pipeline).
`;
}
